### ISSUE TITLE
Folder Project structure

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_GAMABrix#2]
@crisjf I think we should one more level of hierarchy in the root folder to be able to have a .project.

So then when the user clone the repo the Gama_brix folder is a folder containing the project that can be directly imported from GAMA like here
https://github.com/CityScope/CS_Simulation_GAMA/tree/master/CS_CityScope_GAMA

What do you think ? does it make sens for you?

**Comment by crisjf** [comment]
Oh, so the `.project` cannot go in the root folder?

**Comment by crisjf** [comment]
I added `.project` and it's working fine for me.

Let me know if this is not good practice.

**Comment by agrignard** [comment]
Ok we can try like that the only thing is that the README and the gitignoe are at the same level so they are also "imported" in GAMA whereas that are not used but it's a detail (actually it can be a good feature from Gama to provide also a /md reader so you can also have the documentation embedded in GAMA)

let s see how it works like that 

<img width="1775" alt="Screenshot 2021-06-15 at 12 09 05" src="https://user-images.githubusercontent.com/3928502/122035178-800b9100-cdd2-11eb-9582-295c21829381.png">

**Comment by crisjf** [comment]
I like the idea of the md reader. Where can we request a feature like that?

**Comment by agrignard** [comment]
This is the perfect place 
https://github.com/gama-platform/gama/issues

**Comment by crisjf** [comment]
Closing this for now as the folder structure works.
