### ISSUE TITLE
Model template for project

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_GAMABrix#3]
When creating a new model file, I noticed the option of different templates.

![image](https://user-images.githubusercontent.com/8973959/121953846-0f119e00-cd2c-11eb-95e4-028359cf9816.png)

Where are these defined? Can we have a brix-template defined somewhere in the project?

**Comment by agrignard** [comment]
This "template" are actually embedded in GAMA itself it won't be possible to have a GamaBrix template then

**Comment by crisjf** [comment]
That's sad.

**Comment by agrignard** [comment]
Haha, sad I wouldn't say so ;-) The template are here to be always working for any user, what if some Gama users that has no idea about GamaBrix create this kind of template?

However if at somepoint GamaBrix become a plugins then there might be a way to populate the template with a GamaBrix one assuming the plugin is installed. Which could be actually a great feature but again that needs to be implemented at the Gama kevel

**Comment by crisjf** [comment]
Sad that we cannot add project-specific templates.

It'd be cool if users could just clone the repo, open it in gama, and create a new model with the template we provide. 

We should make it a plugin at some point. 

I'll close this for now, but let's keep the idea of turning this feature into a plugin,
